theme: jekyll-theme-midnight
title: "Random, Cloudy, DevOpsy Stuff"
description: "A collection of things related to cloud devops and things I think are interesting"
avatar: images/bitmoji.png

# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ruebroad.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ruebroad

# Build settings
markdown:
  kramdown
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  # syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   # Use existing pygments syntax highlighting css
  #   css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate # Adding pagination capability
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: UA-161773166-1
# permalink: /blog/:year/:month/:day/:title
# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:title

baseurl: ""

footer-links:
  github: ruebroad/ruebroad.github.io

  nav:
  Home:
    - "/"
  Blog:
    - "/blog/"
    - { Categories: "/blog/categories/" }
    - { Tags: "/blog/tags/" }
  Projects:
    - "/projects/"
  Github Project:
    - "http://ruebroad.github.io/"

paginate: 8
paginate_path: "/blog/page:num"

categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/

collections:
  projects:
    output: true
